export const photo = (id, width = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;

export const photos = {
  hero: "/images/hero.jpg",
  villa: "/images/villa.jpg",
  interior: "/images/interior.jpg",
  apartment: "/images/apartment.jpg",
  pool: "/images/pool.jpg",
  home: "/images/home.jpg",
};

export const demoProperties = [
  {
    id: "demo-canarock-1",
    slug: "cana-rock-star-punta-cana",
    title: "Cana Rock Star · Condos con Golf y CONFOTUR",
    location: "Punta Cana",
    type: "Apartamento",
    operation: "Venta",
    price: 178500,
    currency: "USD",
    beds: 2,
    baths: 2,
    area: 95,
    featured: true,
    images: [photos.apartment, photos.pool, photos.interior],
    description:
      "Desarrollo residencial premium dentro del complejo Hard Rock Golf Club en Cana Bay. Cuenta con exención fiscal bajo ley CONFOTUR (15 años sin IPI ni impuesto de transferencia del 3%), piscina infinity estilo resort, club de playa privado y alta rentabilidad garantizada en rentas cortas.",
    amenities: [
      "Ley CONFOTUR",
      "Expediente Auditado GSD",
      "Campo de Golf Hard Rock",
      "Club de Playa Privado",
      "Piscina Infinity Resort",
      "Gimnasio y Restaurante",
      "Seguridad 24/7"
    ],
    demo: true,
  },
  {
    id: "demo-canarock-2",
    slug: "cana-rock-galaxy-punta-cana",
    title: "Cana Rock Galaxy · Vista al Campo de Golf",
    location: "Punta Cana",
    type: "Apartamento",
    operation: "Venta",
    price: 215000,
    currency: "USD",
    beds: 2,
    baths: 2,
    area: 118,
    featured: true,
    images: [photos.hero, photos.interior, photos.pool],
    description:
      "Exclusivo proyecto vacacional y de inversión en Cana Bay con vistas directas al hoyo del campo de golf. Unidades con acabados de primera, amplias terrazas y administración de rentas para inversionistas locales e internacionales.",
    amenities: [
      "Ley CONFOTUR",
      "Expediente Auditado GSD",
      "Vista al Golf",
      "Terraza Panorámica",
      "Piscina Central",
      "Ascensores de Última Generación",
      "Estacionamiento Techado"
    ],
    demo: true,
  },
  {
    id: "demo-1",
    slug: "villa-las-palmas",
    title: "Villa Las Palmas",
    location: "Punta Cana",
    type: "Villa",
    operation: "Venta",
    price: 485000,
    currency: "USD",
    beds: 4,
    baths: 4,
    area: 320,
    featured: true,
    images: [photos.hero, photos.interior, photos.pool],
    description:
      "Espacios abiertos, luz natural y una terraza que se extiende hacia la piscina. Verificado técnicamente y con título saneado listo para traspaso inmediato.",
    amenities: ["Piscina privada", "Terraza", "Jardín", "Expediente Auditado GSD", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-2",
    slug: "residencia-del-parque",
    title: "Residencia del Parque",
    location: "Santo Domingo",
    type: "Apartamento",
    operation: "Venta",
    price: 265000,
    currency: "USD",
    beds: 3,
    baths: 2,
    area: 185,
    featured: true,
    images: [photos.apartment, photos.interior],
    description:
      "Un espacio contemporáneo para vivir la ciudad con calma en el polígono central. Ambientes luminosos, distribución abierta y título libre de gravámenes.",
    amenities: ["Balcón", "Ascensor", "Seguridad 24/7", "Expediente Auditado GSD", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-3",
    slug: "casa-brisa",
    title: "Casa Brisa",
    location: "Puerto Plata",
    type: "Casa",
    operation: "Alquiler",
    price: 2400,
    currency: "USD",
    beds: 3,
    baths: 3,
    area: 240,
    featured: false,
    images: [photos.home, photos.pool, photos.interior],
    description:
      "Una casa pensada para compartir. Jardines, áreas sociales conectadas y una terraza para disfrutar cada día con contrato y soporte jurídico.",
    amenities: ["Jardín", "Terraza", "Piscina", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-4",
    slug: "villa-horizonte",
    title: "Villa Horizonte",
    location: "Samaná",
    type: "Villa",
    operation: "Venta",
    price: 720000,
    currency: "USD",
    beds: 5,
    baths: 5,
    area: 480,
    featured: false,
    images: [photos.villa, photos.pool, photos.interior],
    description:
      "Arquitectura de líneas limpias y áreas generosas en colina con vista a la bahía. Deslinde aprobado y documentación catastral georreferenciada.",
    amenities: ["Piscina privada", "Jardín", "Terraza", "Expediente Auditado GSD", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-5",
    slug: "suite-luz",
    title: "Suite Luz · Cana Bay",
    location: "Punta Cana",
    type: "Apartamento",
    operation: "Alquiler",
    price: 1450,
    currency: "USD",
    beds: 2,
    baths: 2,
    area: 110,
    featured: false,
    images: [photos.interior, photos.apartment, photos.pool],
    description:
      "Apartamento moderno totalmente amueblado a pasos de las amenidades de Cana Bay y playa Arena Gorda.",
    amenities: ["Ascensor", "Balcón", "Piscina", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-6",
    slug: "casa-jardin",
    title: "Casa Jardín",
    location: "Samaná",
    type: "Casa",
    operation: "Venta",
    price: 310000,
    currency: "USD",
    beds: 3,
    baths: 3,
    area: 260,
    featured: false,
    images: [photos.home, photos.interior, photos.pool],
    description:
      "Una residencia rodeada de verde, con espacios que invitan a quedarse y disfrutar en familia, lista para transferencia formal.",
    amenities: ["Jardín", "Terraza", "Expediente Auditado GSD", "Estacionamiento"],
    demo: true,
  },
];
