export const photo = (id, width = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
export const photos = {
  hero: "/images/hero.jpg",
  villa: "/images/villa.jpg",
  interior: "/images/interior.jpg",
  apartment: "/images/apartment.jpg",
  pool: "/images/pool.jpg",
  home: "/images/home.jpg",
};
export const demoProperties = [
  {
    id: "demo-1",
    slug: "villa-las-palmas",
    title: "Villa Las Palmas",
    location: "Punta Cana",
    type: "Villa",
    operation: "Venta",
    price: 485000,
    currency: "USD",
    beds: 4,
    baths: 4,
    area: 320,
    featured: true,
    images: [photos.hero, photos.interior, photos.pool],
    description:
      "Espacios abiertos, luz natural y una terraza que se extiende hacia la piscina. Una propuesta para disfrutar de la vida al aire libre.",
    amenities: ["Piscina privada", "Terraza", "Jardín", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-2",
    slug: "residencia-del-parque",
    title: "Residencia del Parque",
    location: "Santo Domingo",
    type: "Apartamento",
    operation: "Venta",
    price: 265000,
    currency: "USD",
    beds: 3,
    baths: 2,
    area: 185,
    featured: true,
    images: [photos.apartment, photos.interior],
    description:
      "Un espacio contemporáneo para vivir la ciudad con calma. Ambientes luminosos, distribución abierta y detalles que hacen la diferencia.",
    amenities: ["Balcón", "Ascensor", "Seguridad", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-3",
    slug: "casa-brisa",
    title: "Casa Brisa",
    location: "Puerto Plata",
    type: "Casa",
    operation: "Alquiler",
    price: 2400,
    currency: "USD",
    beds: 3,
    baths: 3,
    area: 240,
    featured: true,
    images: [photos.home, photos.pool, photos.interior],
    description:
      "Una casa pensada para compartir. Jardines, áreas sociales conectadas y una terraza para disfrutar cada día.",
    amenities: ["Jardín", "Terraza", "Piscina", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-4",
    slug: "villa-horizonte",
    title: "Villa Horizonte",
    location: "Samaná",
    type: "Villa",
    operation: "Venta",
    price: 720000,
    currency: "USD",
    beds: 5,
    baths: 5,
    area: 480,
    featured: false,
    images: [photos.villa, photos.pool, photos.interior],
    description:
      "Arquitectura de líneas limpias y áreas generosas. Una residencia con espacios para descansar, recibir y disfrutar.",
    amenities: ["Piscina privada", "Jardín", "Terraza", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-5",
    slug: "suite-luz",
    title: "Suite Luz",
    location: "Punta Cana",
    type: "Apartamento",
    operation: "Alquiler",
    price: 1350,
    currency: "USD",
    beds: 2,
    baths: 2,
    area: 110,
    featured: false,
    images: [photos.interior, photos.apartment, photos.pool],
    description:
      "La comodidad de un apartamento luminoso con espacios bien aprovechados para acompañar tu ritmo de vida.",
    amenities: ["Ascensor", "Balcón", "Estacionamiento"],
    demo: true,
  },
  {
    id: "demo-6",
    slug: "casa-jardin",
    title: "Casa Jardín",
    location: "Samaná",
    type: "Casa",
    operation: "Venta",
    price: 310000,
    currency: "USD",
    beds: 3,
    baths: 3,
    area: 260,
    featured: false,
    images: [photos.home, photos.interior, photos.pool],
    description:
      "Una residencia rodeada de verde, con espacios que invitan a quedarse y disfrutar en familia.",
    amenities: ["Jardín", "Terraza", "Estacionamiento"],
    demo: true,
  },
];
